package io.rigor.junkshopserver.junk.junklist;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import io.rigor.junkshopserver.junk.Junk;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.util.List;

@Data
@DynamoDBTable(tableName = "junkList")
@AllArgsConstructor
@NoArgsConstructor
public class JunkList {
  @DynamoDBHashKey
  @DynamoDBAutoGeneratedKey
  private String id;
  @DynamoDBAttribute
  private String receiptNumber;
  @DynamoDBAttribute
  private List<Junk> purchaseItems;
  @DynamoDBAttribute
  private String totalPrice;
  @DynamoDBAttribute
  private String date;
  private String clientId;

}
