package io.rigor.junkshopserver.junk;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

@Data
@DynamoDBTable(tableName = "junk")
@AllArgsConstructor
@NoArgsConstructor
public class Junk {

  @DynamoDBHashKey
  @DynamoDBAutoGeneratedKey
  private String id;
  @DynamoDBAttribute
  private String material;
  @DynamoDBAttribute
  private String price;
  @DynamoDBAttribute
  private String weight;
  @DynamoDBAttribute
  private String totalPrice;
  @DynamoDBAttribute
  private String date; // add by date service etc

}
