package io.rigor.junkshopserver.purchase.PurchaseItem;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

@Data
@DynamoDBTable(tableName = "purchaseItem")
@AllArgsConstructor
@NoArgsConstructor
public class PurchaseItem {
  @DynamoDBHashKey
  @DynamoDBAutoGeneratedKey
  private String id;
  @DynamoDBAttribute
  private String material;
  @DynamoDBAttribute
  private String price;
  @DynamoDBAttribute
  private String weight;
  private String totalPrice;

}
