package io.rigor.junkshopserver.purchase;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import io.rigor.junkshopserver.purchase.PurchaseItem.PurchaseItem;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.util.List;

@DynamoDBTable(tableName = "purchase")
@AllArgsConstructor
@NoArgsConstructor
public class Purchase {

  private String id;
  private List<PurchaseItem> purchaseItems;
  private String totalPrice;
  private String date;

  @DynamoDBHashKey
  @DynamoDBAutoGeneratedKey
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }

  @DynamoDBAttribute
  public List<PurchaseItem> getPurchaseItems() {
    return purchaseItems;
  }

  public void setPurchaseItems(List<PurchaseItem> purchaseItems) {
    this.purchaseItems = purchaseItems;
  }

  @DynamoDBAttribute
  public String getTotalPrice() {
    return totalPrice;
  }

  public void setTotalPrice(String totalPrice) {
    this.totalPrice = totalPrice;
  }

  @DynamoDBAttribute
  public String getDate() {
    return date;
  }

  public void setDate(String date) {
    this.date = date;
  }
}
